FROM eclipse-temurin:17 as builder

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src ./src

RUN chmod +x ./gradlew
RUN ./gradlew bootJar

FROM eclipse-temurin:17

WORKDIR /app

ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DRIVER
ARG DB_DIALECT
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG SESSION_SECRET_KEY
ARG SERVER_SESSION_MAX_AGE

ENV SPRING_DATASOURCE_URL=${DB_URL}
ENV SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DB_DRIVER}
ENV SPRING_JPA_HIBERNATE_DIALECT=${DB_DIALECT}
ENV SPRING_DATA_REDIS_HOST=${REDIS_HOST}
ENV SPRING_DATA_REDIS_PORT=${REDIS_PORT}
ENV SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
ENV SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
ENV SERVER_SERVLET_SESSION_COOKIE_MAX_AGE=${SERVER_SESSION_MAX_AGE}

COPY --from=builder build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app.jar"]